### ISSUE TITLE
No input files, build error

### ISSUE THREAD

**Issue by sean-hill** [VersoSolutions/CordovaClipboard#6]
Hi, after installing this plugin and try to build, I get this error...

```
clang: error: no such file or directory: '/<path>/platforms/ios/memorizeit/Plugins/com.verso.cordova.clipboard/CDVClipboard.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

** BUILD FAILED **


The following build commands failed:
    CompileC build/memorizeit.build/Debug-iphonesimulator/memorizeit.build/Objects-normal/i386/CDVClipboard.o memorizeit/Plugins/com.verso.cordova.clipboard/CDVClipboard.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /<path>/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Any idea why?

**Comment by dcousens** [comment]
@sean-hill can you still replicate this?

**Comment by sean-hill** [comment]
Hey @dcousens, I can't even remember since its been 7 months :)
